name: Zip and publish the bot using Azure CLI

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
  
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./Bot

  deploy:
    runs-on: ubuntu-latest 
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name : Zip      
    - uses: papeloto/action-zip@v1
      with:
          files: /
          dest: result.zip

    - name : Test zip
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ${{ github.workspace }}/result.zip
    

