name: Zip and publish the bot using Azure CLI

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
  
jobs:  
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./Bot

  archive:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'bot.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
