# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Automatic

on:
  push:
    branches:
      - testing
  workflow_dispatch:
  
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install Python dependencies
        working-directory: ./Luis creator
        run: |
          pip install -r requirements.txt
          
      - name: run unittest
        working-directory: ./Luis creator
        run: |
          python -m unittest   
          
  upload:        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./Bot

  deploy:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Login
        uses: azure/login@v1 
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: npm install
        run: |
          npm install

      - name: zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dir.zip bots

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az webapp deployment source config-zip --resource-group "clip10" --name "clibotwebappp" --src "result.zip" 
