name: Pylint and Unittest

on: [push]

defaults:
  run:
    working-directory: ./Luis creator

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: run unittest
        run: |
          python -m unittest   
